[green_agent]
agentbeats_id = ""


[[participants]]
agentbeats_id = ""
agent_id = "GPT-OSS-20"
platform = "OLLAMA"
model="gpt-oss:20b"
api_key = ""


[[participants]]
agentbeats_id = ""
agent_id = "Nemotron"
platform = "OLLAMA"
model = "nemotron-3-nano:30b"
api_key = ""


[config]
max_runs = 5
max_size = 4
required = []
